# Proxies map holds all reverse proxies
proxies:
  service1:
    local: 127.0.0.1:443
    remote: http://127.0.0.1:8080
    tls: true
  
  service2:
    local: 127.0.0.1:9999
    remote: http://192.168.1.20

  service3:
    local: 127.0.0.1:7000
    remote: https://google.com

# CertFile for TLS secured connections
certFile: "certs/cert.crt"

# KeyFile for TLS secured connections
keyFile: "certs/cert.key"

# Logdir is used as destination for the logfile
logdir: "logs"